name: Publish to Docker Hub

on:
  #Push trigger
  push:
    branches:
      - master
      - vlc-support
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'
  #Manual dispatch trigger
  workflow_dispatch:
  #Remote github trigger
  repository_dispatch:
    types: execute
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      
      - name: Extract metadata (tags, labels) for Docker for tags
        id: meta-tag
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=false
          images: doitandbedone/ispyagentdvr
          
      - name: Build and push Docker image for tags
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push tag' }}
          tags: ${{ steps.meta-tag.outputs.tags }}
          labels: ${{ steps.meta-tag.outputs.labels }}
      
      - name: Extract metadata (tags, labels) for Docker for master
        id: meta
        uses: docker/metadata-action@v3
        with:
          tags: |
            # master branch only
            type=match,pattern=master,event=branch
          images: doitandbedone/ispyagentdvr
          
      - name: Build and push Docker image for master
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Extract metadata (tags, labels) for Docker for vlc
        id: meta-vlc
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=false
          tags: |
            # vlc branch only
            type=match,pattern=vlc-support,event=branch
          images: doitandbedone/ispyagentdvr
          
      - name: Build and push Docker image for vlc
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta-vlc.outputs.tags }}
          labels: ${{ steps.meta-vlc.outputs.labels }}
