name: Check for updates and tag
on:
  #Push trigger
  push:
  #Manual dispatch trigger
  workflow_dispatch:
  #Remote github trigger
  repository_dispatch:
    types: execute
  #Run 3 times per day, evenly distributed
  schedule:
    - cron: "* */8 * * *"

jobs:
  build:
    # Job name is Greeting
    name: Update iSpy Agent DVR
    # This runs the job on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Get file name
        run: echo ::set-env name=FILE_LOCATION::$(echo $(wget -qO- "https://www.ispyconnect.com/api/Agent/DownloadLocation2?productID=24&is64=true&platform=Linux" | tr -d '"'))

      - name: Print FILE_LOCATION
        run: echo ${{env.FILE_LOCATION}}

      - name: Get version number
        run: echo ::set-env name=VERSION::$(echo $FILE_LOCATION | grep -Po "(?<=Linux64_).*(?=.zip)" | tr _ .)

      - name: Print VERSION
        run: echo ${{env.VERSION}}
